######################## default configuration ####################
baseURL = "https://jharry34.github.io"
languageCode = "zh-tw"
title = "Harry's Blog"
theme = "liva-hugo"
summaryLength = "10"
pagination.pagerSize = 6
disqusShortname = ""
